" shuff's .vimrc
"
" Don't use abbreviations!  Spelling things out makes grepping easy.
" After installing this .vimrc, run vim-update-bundles to install the
" plugins: https://github.com/bronson/vim-update-bundles

set nocompatible
filetype on   " work around stupid osx bug
filetype off

filetype indent plugin on
syntax on

set encoding=utf-8

set showcmd           " show incomplete cmds down the bottom
set showmode          " show current mode down the bottom

set modeline          " read modelines

set incsearch         " find the next match as we type the search
set hlsearch          " hilight searches by default, unset the register with CR
nnoremap <CR> :noh<CR><CR>
set wrap              " by default, wrap lines (see <leader>w)
set linebreak         " by default, don't break in the middle of a word
set showmatch         " briefly jump to matching }] when typing
set nostartofline     " don't jump to start of line as a side effect (i.e. <<)

set scrolloff=3       " lines to keep visible before and after cursor
set sidescrolloff=7   " columns to keep visible before and after cursor
set sidescroll=1      " continuous horizontal scroll rather than jumpy

set laststatus=2      " always display status line even if only one window is visible.
set updatetime=1000   " reduce updatetime so current tag in taglist is highlighted faster
set autoread          " suppress warnings when git,etc. changes files on disk.
set autowrite         " write buffers before invoking :make, :grep etc.
set nrformats=alpha,hex " C-A/C-X works on dec, hex, and chars (not octal so no leading 0 ambiguity)

set wildmode=list:longest   "make cmdline tab completion similar to bash
set wildmenu                "enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~ "stuff to ignore when tab completing

set backspace=indent,eol,start "allow backspacing over everything in insert mode
set history=1000               "store lots of :cmdline history

set hidden          " allow buffers to go into the background without needing to save

let g:is_posix = 1  " vim's default is archaic bourne shell, bring it up to the 90s.

set visualbell      " don't beep constantly, it's annoying.
set t_vb=           " and don't flash the screen either (terminal anyway...

" search for a tags file recursively from cwd to /
set tags=.tags,tags;/

set writebackup       " keep a backup file, delete after successful write
" Store swapfiles in a single directory.
set backupdir=~/.vim/tmp,/tmp/vim-$USER,/tmp
set directory=~/.vim/tmp,/tmp/vim-$USER,/tmp

" Line numbering
set number

" indenting, languages

set expandtab         " use spaces instead of tabstops
set smarttab          " use shiftwidth when hitting tab instead of sts (?)
set autoindent        " try to put the right amount of space at the beginning of a new line
set shiftwidth=2
set softtabstop=2
set tabstop=2

" fixes

" for Neovim
if has('nvim')
  " Python support
  let g:python_host_prog='/opt/boxen/homebrew/bin/python'

  " Neovim.app options
  if exists('neovim_dot_app')
    "How about a larger starting window?
    set lines=40 columns=100

    " Do not ring the bell, ever
    set visualbell

    " hide gvim's toolbar by default
    set guioptions-=T

    " Tab label is filename, tooltip is full path and file name
    set guitablabel=%t
    set guitabtooltip=%F

    " Always show the tab bar
    set showtabline=2

    " Avoid E173
    if argc() > 1
      silent blast " load last buffer
      silent bfirst " switch back to the first
    endif

  endif
endif

" add a keybinding to toggle paste mode
nnoremap <leader>p :set paste!<CR>:set paste?<CR>

" make ' jump to saved line & column rather than just line.
" http://items.sjbach.com/319/configuring-vim-right
nnoremap ' `
nnoremap ` '

" make Y yank to the end of the line (like C and D).  Use yy to yank the entire line.
" Upside: feels more natural.  Downside: not stock vi/vim.
nmap Y y$

" Make the quickfix window wrap no matter the setting of nowrap
au BufWinEnter * if &buftype == 'quickfix' | setl wrap | endif
" 'q' inside quickfix window closes it (like nerdtree, bufexplorer, etc)
au BufWinEnter * if &buftype == 'quickfix' | map q :cclose<CR> | endif

" Don't use ex mode, use Q for formatting
map Q gq

" Make Alt-Arrows switch between windows (like C-W h, etc)
" nmap <silent> <A-Up> :wincmd k<CR>
" nmap <silent> <A-Down> :wincmd j<CR>
" nmap <silent> <A-Left> :wincmd h<CR>
" nmap <silent> <A-Right> :wincmd l<CR>

" Make Control-direction switch between windows (like C-W h, etc)
nmap <silent> <C-k> :wincmd k<CR>
nmap <silent> <C-j> :wincmd j<CR>
nmap <silent> <C-h> :wincmd h<CR>
nmap <silent> <C-l> :wincmd l<CR>

" quicker to navigate the quickfix window, just control-n, control-p
nmap <silent> <C-n> :cn<CR>
nmap <silent> <C-p> :cp<CR>

" open files from quickfix in a new tab
" http://stackoverflow.com/questions/6852763/vim-quickfix-list-launch-files-in-new-tab#6853779
:set switchbuf+=usetab,newtab

" Pathogen ho!
execute pathogen#infect()

" color schemes
set background=dark
colorscheme solarized
let g:solarized_termcolors=256

" Append modeline after last line in buffer.
nnoremap <silent> <Leader>ml :Modeliner<CR>

" Other custom commands

" Markdown filtering
command -range=% Markdown <line1>,<line2>!markdown

" HTML Tidy filtering
command -range=% HTidy <line1>,<line2>!tidyp -ashtml -wrap 72 -config ~/.vim/tidy/tidy.conf
command -range=% XTidy <line1>,<line2>!tidyp -asxhtml -wrap 0 -config ~/.vim/tidy/tidy.conf

" Airline
let g:airline_powerline_fonts=1

" Vimpager
let vimpager_use_gvim = 0
let vimpager_disable_x11 = 1
let vimpager_scrolloff = 5

" Plugins:

runtime macros/matchit.vim  " enable vim's built-in matchit script (make % bounce between tags, begin/end, etc)

" Syntastic
let g:syntastic_enable_signs=1
let g:syntastic_quiet_messages = { 'level': 'warnings' }
let g:syntastic_auto_loc_list=1
let g:syntastic_perl_lib_path="./lib"
let g:syntastic_shell_checkers = ['shellcheck']
"let g:syntastic_python_checkers = ['flake8']
let g:syntastic_puppet_puppetlint_arguments = '--no-single_quote_string_with_variables-check --no-autoloader_layout-check'
" let g:syntastic_puppet_lint_disable=1

" let g:syntastic_disabled_filetypes = [ 'perl' ]

" Taglist
let g:Tlist_Auto_Open=0
let g:Tlist_Close_On_Select=1
let g:Tlist_Exit_OnlyWindow=1
let g:Tlist_File_Fold_Auto_Close=1
let g:Tlist_Sort_Type="name"
let g:Tlist_Show_Menu=1
let g:Tlist_Use_Right_Window=1
let g:Tlist_WinWidth=30

" vim: set et fenc=utf-8 ff=unix sts=2 sw=2 ts=2 :
